--USE DW_DIARIO_ACADEMICO

CREATE TABLE DIM_TEMPO(
	ID_TEMPO INT IDENTITY (1,1) PRIMARY KEY,
	NIVEL VARCHAR(10),
	SEMESTRE INT,
	NOME_SEMESTRE VARCHAR(50),
	ANO INT,
	PERIODO_LETIVO VARCHAR(6)
);

CREATE TABLE DIM_PROFESSOR(
	ID_PROFESSOR INT IDENTITY (1,1) PRIMARY KEY,
	COD INT,
	MATRICULA_PROFESSOR VARCHAR(12),
	NOME_PROFESSOR VARCHAR(50),
);

CREATE TABLE DIM_DISCIPLINA(
	ID_DISCIPLINA INT IDENTITY (1,1) PRIMARY KEY,
	COD_DISCIPLINA VARCHAR(8), -- codigo da disciplina tipo SINF0075
	COD INT, -- codigo do ambiente operacional
	NOME_DISCIPLINA VARCHAR(50),
);

CREATE TABLE DIM_TURNO(
	ID_TURNO INT IDENTITY (1,1) PRIMARY KEY,
	COD INT,
	NOME_TURNO VARCHAR(50),
);

CREATE TABLE DIM_TURMA(
	ID_TURMA INT IDENTITY (1,1) PRIMARY KEY,
	COD INT,
	NUM_ALUNOS INT,
	NOME_TURMA VARCHAR(10)
);

CREATE TABLE FATO_DIARIO_ACADEMICO(
	ID_TEMPO INT,
	ID_PROFESSOR INT,
	ID_DISCIPLINA INT,
	ID_TURMA INT,
	ID_TURNO INT,
	NUM_APROVADOS INT,
	NUM_REPROVADOS INT,
	NUM_TRANCADOS INT
);

ALTER TABLE FATO_DIARIO_ACADEMICO
ADD CONSTRAINT FK_FATO_DIARIO_ACADEMICO_TO_TEMPO
FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO) --TEMPO

ALTER TABLE FATO_DIARIO_ACADEMICO --PROFESSOR
ADD CONSTRAINT FK_FATO_DIARIO_ACADEMICO_TO_PROFESSOR
FOREIGN KEY (ID_PROFESSOR) REFERENCES DIM_PROFESSOR (ID_PROFESSOR)

ALTER TABLE FATO_DIARIO_ACADEMICO --DISCIPLINA
ADD CONSTRAINT FK_FATO_DIARIO_ACADEMICO_TO_DISCIPLINA
FOREIGN KEY (ID_DISCIPLINA) REFERENCES DIM_DISCIPLINA (ID_DISCIPLINA)

ALTER TABLE FATO_DIARIO_ACADEMICO --TURMA
ADD CONSTRAINT FK_FATO_DIARIO_ACADEMICO_TO_TURMA
FOREIGN KEY (ID_TURMA) REFERENCES DIM_TURMA (ID_TURMA)

ALTER TABLE FATO_DIARIO_ACADEMICO --TURNO
ADD CONSTRAINT FK_FATO_DIARIO_ACADEMICO_TO_TURNO
FOREIGN KEY (ID_TURNO) REFERENCES DIM_TURNO (ID_TURNO)