-- PARA FATO
GO
CREATE OR ALTER PROCEDURE ETL_STAGING_TO_DW_FATO
AS
BEGIN
    DECLARE @ID_TEMPO INT, -- ID QUE DAQUI DA DW
            @ID_DISCIPLINA INT, 
            @ID_PROFESSOR INT,
            @ID_TURMA INT,
            @ID_TURNO INT,
            @COD_TEMPO INT, -- ID QUE VEM DA STAGING
            @COD_DISCIPLINA INT, 
            @COD_PROFESSOR INT,
            @COD_TURMA INT,
            @COD_TURNO INT,
            @NUM_APROVADOS INT,
            @NUM_REPROVADOS INT,
            @NUM_TRANCADOS INT,
            @ANO INT,
            @SEMESTRE INT

    DECLARE CURSOR_FATO CURSOR FOR
    SELECT COD_TEMPO, COD_DISCIPLINA, COD_PROFESSOR, COD_TURMA, COD_TURNO, NUM_APROVADOS, NUM_REPROVADOS, NUM_TRANCADOS
    FROM AUX_FATO F

	OPEN CURSOR_FATO
	FETCH CURSOR_FATO INTO @COD_TEMPO, @COD_DISCIPLINA, @COD_PROFESSOR, @COD_TURMA, @COD_TURNO, @NUM_APROVADOS, @NUM_REPROVADOS, @NUM_TRANCADOS
	
    WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @ID_DISCIPLINA = (SELECT ID_DISCIPLINA FROM DIM_DISCIPLINA D WHERE D.ID_DISCIPLINA = @COD_DISCIPLINA)
		SET @ID_PROFESSOR = (SELECT ID_PROFESSOR FROM DIM_PROFESSOR P WHERE P.ID_PROFESSOR = @COD_PROFESSOR)
		SET @ID_TURMA = (SELECT ID_TURMA FROM DIM_TURMA TM WHERE TM.ID_TURMA = @COD_TURMA)
		SET @ID_TURNO = (SELECT ID_TURNO FROM DIM_TURNO TN WHERE TN.ID_TURNO = @COD_TURNO)
        SET @ID_TEMPO = (SELECT ANO, SEMESTRE FROM DIM_TEMPO T WHERE T.ANO = @ANO AND T.SEMESTRE = @SEMESTRE)
		
		INSERT INTO FATO_DIARIO_ACADEMICO(ID_TEMPO, ID_DISCIPLINA, ID_PROFESSOR, ID_TURMA, ID_TURNO, NUM_APROVADOS, NUM_REPROVADOS, NUM_TRANCADOS)
		VALUES(@ID_TEMPO, @ID_DISCIPLINA, @ID_PROFESSOR, @ID_TURMA, @ID_TURNO, @NUM_APROVADOS, @NUM_REPROVADOS, @NUM_TRANCADOS)

		FETCH CURSOR_FATO INTO @COD_TEMPO, @COD_DISCIPLINA, @COD_PROFESSOR, @COD_TURMA, @COD_TURNO, @NUM_APROVADOS, @NUM_REPROVADOS, @NUM_TRANCADOS, @ANO, @SEMESTRE
	END
	CLOSE CURSOR_FATO
	DEALLOCATE CURSOR_FATO
END

GO