-- STAGING PARA DW
-- PARA TURMA
GO
CREATE OR ALTER PROCEDURE ETL_STAGING_TO_DW_PROFESSOR
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @ID_TURNO INT, 
			@MATRICULA_PROFESSOR VARCHAR(12),
			@NOME_PROFESSOR VARCHAR(50)

	DECLARE C_PROFESSOR CURSOR
		FOR SELECT P.ID_PROFESSOR, P.MATRICULA_PROFESSOR, P.NOME_PROFESSOR FROM AUX_PROFESSOR P

	OPEN C_PROFESSOR
	FETCH C_PROFESSOR INTO @ID_PROFESSOR, @MATRICULA_PROFESSOR, @NOME_PROFESSOR

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- VERIFICA SE O PROFESSOR NAO EXISTE NO DW
		IF NOT EXISTS (SELECT * FROM DIM_PROFESSOR P WHERE P.COD = @ID_PROFESSOR )
		BEGIN
			INSERT INTO DIM_PROFESSOR(COD, MATRICULA_PROFESSOR,NOME_PROFESSOR)
			VALUES(@ID_PROFESSOR, @MATRICULA_PROFESSOR, @NOME_PROFESSOR)
		END
		
		FETCH C_PROFESSOR INTO @ID_PROFESSOR, @MATRICULA_PROFESSOR, @NOME_PROFESSOR
	END
	CLOSE C_PROFESSOR
	DEALLOCATE C_PROFESSOR
END
GO