--USE DW_DIARIO_ACADEMICO
CREATE OR ALTER PROCEDURE ETL_OLTP_TO_STAGING_TURMA(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE AUX_TURMA WHERE DATACARGA = @DATA_CARGA

	INSERT INTO AUX_TURMA(DATACARGA,ID_TURMA,NUM_ALUNOS,NOME_TURMA)
	SELECT @DATA_CARGA, TM.ID_TURMA, TM.NUM_ALUNOS, TM.NOME_TURMA FROM TB_TURMA TM
END
