--CREATE DATABASE DW_DIARIO_ACADEMICO
--USE DW_DIARIO_ACADEMICO

CREATE TABLE TB_ALUNO(
	ID_ALUNO INT IDENTITY (1,1) PRIMARY KEY,
	MATRICULA_ALUNO VARCHAR(12),
	NOME_ALUNO VARCHAR(50),
);

CREATE TABLE TB_ALUNO_TURMA(
	ID_TURMA INT,
	ID_ALUNO INT,
	STATUS VARCHAR(60)
);
CREATE TABLE TB_TURMA(
	ID_TURMA INT IDENTITY (1,1) PRIMARY KEY,
	ID_PROFESSOR INT,
	ID_TURNO INT,
	ID_DISCIPLINA INT,
	NUM_ALUNOS INT,
	ANO INT,
	SEMESTRE INT,
);

CREATE TABLE TB_PROFESSOR(
	ID_PROFESSOR INT IDENTITY (1,1) PRIMARY KEY,
	MATRICULA_PROFESSOR VARCHAR(12), -- MUDEI PARA VARCHAR
	NOME_PROFESSOR VARCHAR(50),
);

CREATE TABLE TB_DISCIPLINA(
	ID_DISCIPLINA INT IDENTITY (1,1) PRIMARY KEY,
	COD_DISCIPLINA VARCHAR(8), 
	NOME_DISCIPLINA VARCHAR(50),
	NUM_TURMAS INT,
);

CREATE TABLE TB_TURNO(
	ID_TURNO INT IDENTITY (1,1) PRIMARY KEY,
	NOME_TURNO CHAR(1) CHECK (NOME_TURNO IN ('M','V','N')) -- MATUTINO, VESPERTINO E NOTURNO
);


ALTER TABLE TB_ALUNO_TURMA
ADD CONSTRAINT FK_ALUNO_TURMA_TO_ALUNO
FOREIGN KEY (ID_ALUNO) REFERENCES TB_ALUNO (ID_ALUNO)

ALTER TABLE TB_ALUNO_TURMA
ADD CONSTRAINT FK_ALUNO_TURMA_TO_TURMA
FOREIGN KEY (ID_TURMA) REFERENCES TB_TURMA (ID_TURMA)

ALTER TABLE TB_TURMA
ADD CONSTRAINT FK_TURMA_TO_PROFESSOR
FOREIGN KEY (ID_PROFESSOR) REFERENCES TB_PROFESSOR (ID_PROFESSOR)

ALTER TABLE TB_TURMA
ADD CONSTRAINT FK_TURMA_TO_TURNO 
FOREIGN KEY (ID_TURNO) REFERENCES TB_TURNO (ID_TURNO)

ALTER TABLE TB_TURMA
ADD CONSTRAINT FK_TURMA_TO_DISCIPLINA
FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_DISCIPLINA (ID_DISCIPLINA)