--USE DW_DIARIO_ACADEMICO

CREATE TABLE AUX_PROFESSOR(
	ID_PROFESSOR INT PRIMARY KEY,
	MATRICULA_PROFESSOR VARCHAR(12),
	NOME_PROFESSOR VARCHAR(50),
	DATACARGA DATETIME
);

CREATE TABLE AUX_DISCIPLINA(
	ID_DISCIPLINA INT PRIMARY KEY,
	COD_DISCIPLINA VARCHAR(8), -- CODIGO DA DISCIPLINA AUDS1205
	NOME_DISCIPLINA VARCHAR(50),
	NUM_TURMAS INT,
	DATACARGA DATETIME
);

CREATE TABLE AUX_TURNO(
	ID_TURNO INT PRIMARY KEY,
	NOME_TURNO CHAR(1),
	DATACARGA DATETIME
);

CREATE TABLE AUX_TURMA(
	ID_TURMA INT PRIMARY KEY,
	NUM_ALUNOS INT,
	DATACARGA DATETIME
);

CREATE TABLE AUX_FATO(
	ID_TEMPO INT,
	ID_PROFESSOR INT,
	ID_DISCIPLINA INT,
	ID_TURMA INT,
	ID_TURNO INT,
	NUM_APROVADOS INT,
	NUM_REPROVADOS INT,
	NUM_TRANCADOS INT,
	DATACARGA DATETIME
);

CREATE TABLE VIO_FATO(
	ID_TEMPO INT,
	ID_PROFESSOR INT,
	ID_DISCIPLINA INT,
	ID_TURMA INT,
	ID_TURNO INT,
	NUM_APROVADOS INT,
	NUM_REPROVADOS INT,
	NUM_TRANCADOS INT,
	DATACARGA DATETIME
);