CREATE OR ALTER PROCEDURE AGGREGATE_APROVACAO_PROFESSOR_ANO
AS
BEGIN
    DECLARE @ID_ANO INT,
			@ANO INT,
			@ID_PROFESSOR INT,
			@TOTAL_APROVACAO INT

	DECLARE C_TEMPO CURSOR FOR 
		SELECT ID_TEMPO, ANO FROM DIM_TEMPO WHERE NIVEL = 'ANO'

	DELETE FATO_APROVACAO_PROFESSOR_ANO

	OPEN C_TEMPO
	FETCH C_TEMPO INTO @ID_ANO, @ANO
	WHILE @@FETCH_STATUS = 0
	BEGIN
		INSERT INTO FATO_APROVACAO_PROFESSOR_ANO(ID_ANO, ID_PROFESSOR, TOTAL_APROVACAO)
		SELECT @ID_ANO, DA.ID_PROFESSOR, SUM(DA.NUM_APROVADOS) AS TOTAL_APROVACAO
		FROM FATO_DIARIO_ACADEMICO DA
		JOIN DIM_TEMPO T
		ON DA.ID_TEMPO = T.ID_TEMPO
		WHERE T.ANO = @ANO
		GROUP BY DA.ID_PROFESSOR

		FETCH C_TEMPO INTO @ID_ANO, @ANO

	END
	CLOSE C_TEMPO
	DEALLOCATE C_TEMPO
END

GO

DELETE FATO_APROVACAO_PROFESSOR_ANO

EXEC AGGREGATE_APROVACAO_PROFESSOR_ANO

SELECT P.NOME_PROFESSOR, T.ANO, F.TOTAL_APROVACAO 
FROM FATO_APROVACAO_PROFESSOR_ANO F 
JOIN DIM_PROFESSOR P 
ON F.ID_PROFESSOR = P.ID_PROFESSOR 
JOIN DIM_TEMPO T 
ON T.ID_TEMPO = F.ID_ANO