--CREATE DATABASE DW_DIARIO_ACADEMICO
--USE DW_DIARIO_ACADEMICO

CREATE TABLE TB_ALUNO(
	ID_ALUNO INT PRIMARY KEY,
	COD_ALUNO INT,
	MATRICULA_ALUNO INT,
	NOME_ALUNO VARCHAR(50),
);

CREATE TABLE TB_PROFESSOR(
	ID_PROFESSOR INT PRIMARY KEY,
	COD_PROFESSOR INT,
	MATRICULA_PROFESSOR INT,
	NOME_PROFESSOR VARCHAR(50),
);

CREATE TABLE TB_DISCIPLINA(
	ID_DISCIPLINA INT PRIMARY KEY,
	COD_DISCIPLINA INT,
	NOME_DISCIPLINA VARCHAR(50),
	NUM_TURMAS INT,
	ID_TURMA INT,
);

CREATE TABLE TB_TURNO(
	ID_TURNO INT PRIMARY KEY,
	COD_TURNO INT,
	NOME_TURNO VARCHAR(50),
);

CREATE TABLE TB_TURMA(
	ID_TURMA INT PRIMARY KEY,
	COD_TURMA INT,
	NUM_ALUNOS INT,
	ID_PROF INT,
	ID_TURNO INT,
	ANO DATETIME,
	SEMESTRE DATETIME,
);
