

CREATE OR ALTER PROCEDURE ETL_OLTP_TO_STAGING_TURNO(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE AUX_TURNO WHERE DATACARGA = @DATA_CARGA

	INSERT INTO AUX_TURNO(DATACARGA,ID_TURNO,NOME_TURNO)
	SELECT @DATA_CARGA, T.ID_TURNO, T.NOME_TURNO FROM TB_TURNO T 
END

EXEC ETL_OLTP_TO_STAGING_TURNO '20221115'
SELECT * FROM AUX_TURNO