

CREATE OR ALTER PROCEDURE ETL_STAGING_TO_DW_TURNO
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @ID_TURNO INT, @NOME_TURNO VARCHAR(50)

	DECLARE C_TURNO CURSOR
		FOR SELECT T.ID_TURNO, T.NOME_TURNO FROM AUX_TURNO T

	OPEN C_TURNO
	FETCH C_TURNO INTO @ID_TURNO, @NOME_TURNO

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- VERIFICA SE O TURNO NAO EXISTE NO DW
		IF NOT EXISTS (SELECT T.ID_TURNO FROM DIM_TURNO T WHERE T.ID_TURNO = @ID_TURNO )
		BEGIN
			INSERT INTO DIM_TURNO(COD, NOME_TURNO)
			VALUES(@ID_TURNO, @NOME_TURNO)
		END
		-- SE O TURNO JA EXISTE NO DW ELE ATUALIZA
		ELSE
		BEGIN
			UPDATE DIM_TURNO
			SET NOME_TURNO = @NOME_TURNO
			WHERE COD = @ID_TURNO 
		END
		FETCH C_TURNO INTO @ID_TURNO, @NOME_TURNO
	END
	CLOSE C_TURNO
	DEALLOCATE C_TURNO
END

EXEC ETL_STAGING_TO_DW_TURNO
SELECT * FROM DIM_TURNO