-- AMBIENRE OPERACINAL PARA STAGING
--DISCIPLINA
GO
CREATE OR ALTER PROCEDURE ETL_OLTP_TO_STAGING_DISCIPLINA(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM AUX_DISCIPLINA WHERE DATACARGA = @DATA_CARGA

	INSERT INTO AUX_DISCIPLINA(DATACARGA, ID_DISCIPLINA, COD_DISCIPLINA, NOME_DISCIPLINA)
	SELECT @DATA_CARGA, D.ID_DISCIPLINA, D.COD_DISCIPLINA, D.NOME_DISCIPLINA FROM TB_DISCIPLINA D
END
GO
--TURMA
GO
CREATE OR ALTER PROCEDURE ETL_OLTP_TO_STAGING_TURMA(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM AUX_TURMA WHERE DATACARGA = @DATA_CARGA

	INSERT INTO AUX_TURMA(DATACARGA,ID_TURMA,NUM_ALUNOS,NOME_TURMA)
	SELECT @DATA_CARGA, TM.ID_TURMA, TM.NUM_ALUNOS, TM.NOME_TURMA FROM TB_TURMA TM
END
GO

--TURNO
GO
CREATE OR ALTER PROCEDURE ETL_OLTP_TO_STAGING_TURNO(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM AUX_TURNO WHERE DATACARGA = @DATA_CARGA

	INSERT INTO AUX_TURNO(DATACARGA,ID_TURNO,NOME_TURNO)
	SELECT @DATA_CARGA, T.ID_TURNO, T.NOME_TURNO FROM TB_TURNO T 
END
GO
--PROFESSOR
GO
CREATE OR ALTER PROCEDURE ETL_OLTP_TO_STAGING_PROFESSOR(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM AUX_PROFESSOR WHERE DATACARGA = @DATA_CARGA

	INSERT INTO AUX_PROFESSOR(DATACARGA, ID_PROFESSOR, MATRICULA_PROFESSOR, NOME_PROFESSOR)
	SELECT @DATA_CARGA, P.ID_PROFESSOR, P.MATRICULA_PROFESSOR, P.NOME_PROFESSOR FROM TB_PROFESSOR P 
END
GO
--FATO
GO
CREATE OR ALTER PROCEDURE ETL_OLTP_TO_STAGING_FATO(@DATA_CARGA DATETIME,@ANO_INICIO INT,@ANO_FIM INT)
AS
BEGIN
	DECLARE @ID_TURMA INT,
			@ID_PROFESSOR INT,
			@ID_DISCIPLINA INT,
			@ID_TURNO INT,
			@NUM_ALUNOS INT,
			@NUM_APROVADOS INT,
			@NUM_REPROVADOS INT,
			@NUM_TRANCADOS INT,
			@ANO INT,
			@SEMESTRE INT

	DELETE FROM AUX_FATO WHERE DATACARGA = @DATA_CARGA AND ANO>=@ANO_INICIO AND ANO<=@ANO_FIM  

	DECLARE C_TURMA 
	CURSOR FOR SELECT T.ID_TURMA, T.ID_PROFESSOR, T.ID_DISCIPLINA,T.ID_TURNO, T.NUM_ALUNOS, T.ANO, T.SEMESTRE FROM TB_TURMA T WHERE T.ANO>=@ANO_INICIO AND T.ANO<=@ANO_FIM

	OPEN C_TURMA
	FETCH C_TURMA INTO @ID_TURMA, @ID_PROFESSOR, @ID_DISCIPLINA, @ID_TURNO, @NUM_ALUNOS, @ANO, @SEMESTRE

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- CRIAR UMA TURMA COM QUANTIDADE ALUNO 0
		IF @NUM_ALUNOS = 0
		BEGIN
			INSERT INTO VIO_FATO(DATACARGA,ID_TURMA,ID_PROFESSOR,ID_DISCIPLINA,ID_TURNO,NUM_APROVADOS, 
				NUM_REPROVADOS,NUM_TRANCADOS,ANO,SEMESTRE,DATA_ERRO, VIOLACAO) 
			VALUES(@DATA_CARGA,@ID_TURMA,@ID_PROFESSOR,@ID_DISCIPLINA,@ID_TURNO,@NUM_APROVADOS,
				@NUM_REPROVADOS,@NUM_TRANCADOS,@ANO,@SEMESTRE,GETDATE(),'TURMA SEM ALUNOS');
		END 
		ELSE
		BEGIN

			SET @NUM_APROVADOS = (SELECT COUNT(*) FROM TB_ALUNO_TURMA AT WHERE AT.ID_TURMA = @ID_TURMA AND AT.STATUS = 'APROVADO')

			SET @NUM_REPROVADOS = (SELECT COUNT(*) FROM TB_ALUNO_TURMA AT WHERE AT.ID_TURMA = @ID_TURMA AND AT.STATUS = 'REPROVADO')

			SET @NUM_TRANCADOS = (SELECT COUNT(*) FROM TB_ALUNO_TURMA AT WHERE AT.ID_TURMA = @ID_TURMA AND AT.STATUS = 'TRANCADO')

			INSERT INTO AUX_FATO(DATACARGA,ID_PROFESSOR,ID_DISCIPLINA,ID_TURMA,ID_TURNO,NUM_APROVADOS,NUM_REPROVADOS,NUM_TRANCADOS,ANO,SEMESTRE) VALUES (@DATA_CARGA,@ID_PROFESSOR,@ID_DISCIPLINA,@ID_TURMA,@ID_TURNO,@NUM_APROVADOS,@NUM_REPROVADOS,@NUM_TRANCADOS,@ANO,@SEMESTRE)
		END
		FETCH C_TURMA INTO @ID_TURMA, @ID_PROFESSOR, @ID_DISCIPLINA, @ID_TURNO, @NUM_ALUNOS, @ANO, @SEMESTRE
	END
	CLOSE C_TURMA
	DEALLOCATE C_TURMA

END
GO

-- DQL
GO
CREATE OR ALTER PROCEDURE ETL_TODOS_PROCEDURE(@DATA_CARGA DATETIME, @ANO_INICIAL INT, @ANO_FINAL INT)
AS
BEGIN
	EXEC ETL_OLTP_TO_STAGING_DISCIPLINA @DATA_CARGA
	EXEC ETL_OLTP_TO_STAGING_TURMA @DATA_CARGA
	EXEC ETL_OLTP_TO_STAGING_TURNO @DATA_CARGA
	EXEC ETL_OLTP_TO_STAGING_PROFESSOR @DATA_CARGA
    
	EXEC ETL_OLTP_TO_STAGING_FATO @DATA_CARGA, @ANO_INICIAL, @ANO_FINAL
END

EXEC ETL_TODOS_PROCEDURE '20221123', 2020, 2022
SELECT * FROM AUX_DISCIPLINA
SELECT * FROM AUX_TURMA
SELECT * FROM AUX_TURNO
SELECT * FROM AUX_PROFESSOR
SELECT * FROM AUX_FATO
SELECT * FROM VIO_FATO